language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: LINE
  password:
    secure: Lc3H/EcwJcZnhnJ5URbZ6z663nmd7fIHQzC9MZ7X0KsoZM3BYx9pdFTPZ0C78t9nRbqOwossThJQy9f2an4367SGowetGjSqKXD9JeR6aONTCA5+VlI4SNSGqK+KSryi0a5t80W9kHDaCO5ssjFoT9u1OzjDrTI3Mg5jimy2HYsM9uI2vceKt2VLi3Qk2P7ZJfBAGHk2G8CRGquqv/Zf7f8HE0ivcIUjRASXuJwihwmVBQoclIaOqLnn/WZgaxLwn2stSXpEdQuWjlWD+VTZEaLA4/gSpcZAMAwBlesMdD4pJo6K+0PCe3LwU0I58kMLaBOfX/Vf6bklq0uMnNhQGvpBPAOwHyahgEvQBmbHP602i0MZEwMc1nhJ3rtZDmhmOcaZHfu4Qcw6Gd1dU10duVJtVcbipBglMDqGvU/SPTifj272ZkQL1x78gehZuAjYs8NWb3qUfpnVfz0ZMdGh6fmhWKNy8vSij2vzstSl7m2FSTDEKXkFLtS1mWd0Lavgg1Z+DiZuqAsDkghizSszB3LDGqtZ+9hp67CMKDtlKmWYRRtPCrYjH9i+b2ebcfSGhykai7V8iwE0xRLtGCc045nGK8SkEcZOJhNKeeclp3ow7zmhmYdOMR904/TamW84Mbn5+xo3Y+UkEWswLHYWbL4w0SUIsCQTNFPBv/lXs8s=
